services:
 db_mysql:                     # db foi o nome que escolhi para este service do MySql
  image: mysql:5.7
  volumes:
    - db_data:/var/lib/mysql   # É pode ser uma coleção
  restart: always              # Compose irá reinicar a cada nova atualização
  environment:                 # Variáveis de ambiente para o serviço do MySQL
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: my_database_test
    MYSQL_USER: dev
    MYSQL_PASSWORD: secret
  ports:
    - 8083:3306
volumes:
  db_data: {}